
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host  # Use host network mode
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - npm-cache:/root/.npm  # Cache npm packages to avoid reinstalling

volumes:
  npm-cache:
