services:
  one-more-battery-main:
    image: one-more-battery:latest
    container_name: one-more-battery-main
    ports:
      - "80:4200"
    command: >
      ng serve --host 0.0.0.0 --poll=2000 --port 4200 --disable-host-check
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
